#!/bin/sh
# script/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.


set -e
BASE_DIR=$(cd `dirname $0`/../; pwd)
cd $BASE_DIR

function up() {
  BASE_NAME=$1
  BUILD_WAR="build/libs/${BASE_NAME}##${CIRCLE_BUILD_NUM}.war"
  cp build/libs/$BASE_NAME.war $BUILD_WAR
  upload $BUILD_WAR
}
function upload() {
  ruby $BASE_DIR/script/upload.rb $*
}

echo "Tests started at..."
date "+%H:%M:%S"

echo "Running tests ..."
date "+%H:%M:%S"

sh script/test

ruby script/upload.rb

#cd common
#./gradlew clean eclipse build

#cd ../api
#./gradlew clean eclipse buildWeb -x test
#up api

#cd ../front
#./gradlew clean eclipse buildWeb -x test
#up front

#cd ../management
#./gradlew clean eclipse buildWeb -x test
#up management

cd $BASE_DIR
