#!/bin/sh
# script/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.


set -e
BASE_DIR=$(cd `dirname $0`/../; pwd)
cd $BASE_DIR

pwd
echo "Ci Building, and env value[$CI_SAMPLE_VALUE]"
sh $BASE_DIR/script/test
