#!/bin/sh
# script/console: Launch a console for the application. Optionally allow an
#                 environment to be passed in to let the script handle the
#                 specific requirements for connecting to a console for that
#                 environment.


set -e
BASE_DIR=$(cd `dirname $0`/../; pwd)
cd $BASE_DIR

echo "Do Nothing!!"
