#!/bin/sh
# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e
BASE_DIR=$(cd `dirname $0`/../; pwd)
cd $BASE_DIR

sh $BASE_DIR/script/bootstrap
