#!/bin/sh
# script/test: Run test suite for application. Optionallly pass in a path to an
#              individual test file to run a single test.

set -e
BASE_DIR=$(cd `dirname $0`/../; pwd)
cd $BASE_DIR

echo "Runing test."
